#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-htmlls "C:\Users\mailr\.GIT\rafafs.github.io\" | grep gemspec
# ou
dir "C:\Users\mailr\.GIT\rafafs.github.io\jekyll-theme-hacker.gemspec"